### PR TITLE
chore: bump deno std

### PR DESCRIPTION
**Pull request by talentlessguy**
bump deno folder's std imports to latest

### CODE REVIEW

**Review by shadowtime2000 — CHANGES_REQUESTED** [review]
The `deno_dist` folder is for the build output of denoify, could you update the version in `src/file-methods.deno.ts` instead?

**Comment by talentlessguy** [comment]
@shadowtime2000 done

**Comment by shadowtime2000** [comment]
Can you remove your changes from the `deno_dist` folder?

**Comment by talentlessguy** [comment]
@shadowtime2000 removed it

**Comment by talentlessguy** [comment]
oh ooops i accidentally deleted the whole folder... not the changes, one sec imma fix it

**Comment by talentlessguy** [comment]
done

@shadowtime2000

**Pull request merged**
