### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by guildenstern70**
Added SmartDeno as 'eta' reference

### CODE REVIEW

**Comment by nebrelbug** [comment]
@guildenstern70 thanks for the PR! Is the code for SmartDeno open source by any chance?

**Comment by guildenstern70** [comment]
It is: MIT License. https://github.com/guildenstern70/SmartDeno

**Comment by guildenstern70** [comment]
Done

**Review by nebrelbug — APPROVED** [review]

**Comment by nebrelbug** [comment]
@guildenstern70 perfect, thank you! I'll merge now.

**Pull request merged**
