### PR TITLE
Disable package-lock.json

### PR DESCRIPTION
**Pull request by gurgunday**

### CODE REVIEW

**Review by nebrelbug — APPROVED** [review]

**Comment by nebrelbug** [comment]
@gurgunday thanks! This looks good.

**Comment by gurgunday** [comment]
Well, it should be fine if SemVer is respected by the dependencies

You mean reproducibility after cloning right? Cause `package-lock` isn't included in the NPM registry anyway

**Comment by gurgunday** [comment]
Right now, do you have any issues when you clone the repository and do an `npm i`?

Look, this is one of those subjects where there isn't a single _right way_ to go about things — it's subjective!

If maintainers don't regularly update the lock file, you end up with vulnerable packages. Also, when you say typically, you need to provide some examples, because from [what](https://github.com/stripe/stripe-node/commit/bf7f2d9a631ea9d7517895da97ad58cdfa3c3940) [I](https://github.com/eslint/eslint/#why-doesnt-eslint-lock-dependency-versions) [see](https://www.twilio.com/blog/lockfiles-nodejs), [typically](https://github.com/fastify/fastify/blob/bc3f95734581c1fa22e1c4a4da9b898cf9e3ec7f/.gitignore#L138), it's kinda the norm to remove it for libraries.

In any case, I don't have a strong opinion on this matter, so you can ask @nebrelbug to get a definitive answer.

**Comment by nebrelbug** [comment]
@gurgunday @legobeat I appreciate the discussion about this issue. 

I think a lot of the benefits of having a package-lock.json don't necessarily apply in this case, since Eta has no direct dependencies -- just development dependencies. This means that users won't get notified about security vulnerabilities when installing Eta which aren't necessarily relevant.

I do think it's worth considering adding back `package-lock.json` just because -- depending on how we set up CI -- it could speed up builds. Let's add this to the list of todo items for v3. We can evaluate further after we design the v3 CI build process, which I want to migrate entirely to GitHub Actions.

**Pull request merged**
