### PR TITLE
doc: clarify import syntax

### PR DESCRIPTION
**Pull request by hamzahamidi**

### CODE REVIEW

**Review by nebrelbug — APPROVED** [review]
Thank you! This looks great.

**Comment by nebrelbug** [comment]
@hamzahamidi do you mind if I add you to the README as a contributor?

**Comment by hamzahamidi** [comment]
@nebrelbug Not at all. Thank you. Great Lib btw. I came across it thanks to docusaurus.

**Comment by nebrelbug** [comment]
@hamzahamidi thank you! I'm glad you like the library.

@all-contributors please add @hamzahamidi for documentation :tada:

**Comment by nebrelbug** [comment]
@hamzahamidi just added you to the README :)

Thanks again for the PR!

**Pull request merged**
